ekyna_subscription_pricing_admin_home:
    path: ""
    defaults: { _controller: "ekyna_subscription.pricing.controller:homeAction" }
    methods: [GET]

ekyna_subscription_pricing_admin_generate_notify:
    path: /generate-notify
    defaults: { _controller: "ekyna_subscription.pricing.controller:generateNotifyAction" }
    methods: [GET|POST]

ekyna_subscription_pricing_admin_list:
    path: /list
    defaults: { _controller: "ekyna_subscription.pricing.controller:listAction" }
    methods: [GET|POST]

ekyna_subscription_pricing_admin_new:
    path: /new
    defaults: { _controller: "ekyna_subscription.pricing.controller:newAction" }
    methods: [GET|POST]

ekyna_subscription_pricing_admin_show:
    path: /{pricingId}/show
    defaults: { _controller: "ekyna_subscription.pricing.controller:showAction" }
    methods: [GET|POST]
    requirements:
        pricingId: \d+

ekyna_subscription_pricing_admin_edit:
    path: /{pricingId}/edit
    defaults: { _controller: "ekyna_subscription.pricing.controller:editAction" }
    methods: [GET|POST]
    requirements:
        pricingId: \d+

ekyna_subscription_pricing_admin_remove:
    path: /{pricingId}/remove
    defaults: { _controller: "ekyna_subscription.pricing.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        pricingId: \d+

ekyna_subscription_pricing_admin_subscription_toggle_exempt:
    path: /{pricingId}/subscriptions/{subscriptionId}/toggle-exempt
    defaults: { _controller: "ekyna_subscription.pricing.controller:subscriptionToggleExemptAction" }
    methods: [GET]
    requirements:
        pricingId: \d+
        subscriptionId: \d+
