winzou_state_machine:
    ekyna_subscription:
        class:         Ekyna\Bundle\SubscriptionBundle\Model\SubscriptionInterface
        property_path: state
        states:
            new: ~
            pending: ~
            valid: ~
            exempt: ~
        transitions:
            lock:
                from: [new]
                to:   pending
            validate:
                from: [new, pending]
                to:   valid
            unlock:
                from: [pending, valid]
                to:   new
            exempt:
                from: [new]
                to:   exempt
            unexempt:
                from: [exempt]
                to:   new
