ekyna_subscription_account_index:
    path: ""
    defaults:
        _controller: EkynaSubscriptionBundle:Account:index
    methods: [GET]
    options:
        _cms:
            name: "Mes cotisations"
            parent: ekyna_user_account_home
            seo:
                follow: false
                index: false

ekyna_subscription_account_payment:
    path: /payment
    defaults:
        _controller: EkynaSubscriptionBundle:Account:payment
    methods: [GET|POST]
    options:
        _cms:
            name: "Régler mes cotisations"
            parent: ekyna_subscription_account_index
            seo:
                follow: false
                index: false
